version: "3.3"
services:
  crt:
    build:
      context: .
      dockerfile: crt.Dockerfile
    volumes:
      - ./private:/etc/v2ray
    ports:
      - 80:80

  v2ray:
    build:
      context: .
      dockerfile: v2ray.Dockerfile
    container_name: v2ray
    env_file:
      - .env
    volumes:
      - ./config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  haproxy:
    image: "haproxy:2.5-alpine"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
      - :/etc/ssl/private
