version: "3.3"
services:
  haproxy:
    image: "haproxy:2.5-alpine"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
      - /etc/v2ray:/etc/ssl/private
    ports:
      - 443:443
    networks:
      - v2ray
  v2ray:
    build:
      context: .
      dockerfile: v2ray.Dockerfile
    container_name: v2ray
    volumes:
      - ./config:/config
    expose:
      - 40001
    restart: unless-stopped
    networks:
      - v2ray
  nginx:
    image: "nginx"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 8080
    networks:
      - v2ray
networks:
  v2ray:
    external: true
