version: "3.3"
services:
  haproxy:
    build:
      context: .
      dockerfile: haproxy.Dockerfile
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    volumes:
      - /etc/haproxy:/usr/local/etc/haproxy
      - /etc/v2ray:/etc/ssl/private
    user:
      - root
    entrypoint: ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
    ports:
      - 443:443
    networks:
      - v2ray
  v2ray:
    image: v2ray/official
    container_name: v2ray
    volumes:
      - /etc/v2ray/config.json:/etc/v2ray/config.json
    entrypoint: ["v2ray", "-config=/etc/v2ray/config.json"]
    expose:
      - 40001
    restart: unless-stopped
    networks:
      - v2ray
  nginx:
    image: "nginx"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 8080
    networks:
      - v2ray
networks:
  v2ray:
    external: true
